FROM microsoft/dotnet:2.0-sdk
WORKDIR /sample-app/

COPY *.csproj ./
RUN dotnet restore

COPY . ./sample-app
RUN dotnet build -c Release
ENTRYPOINT ["dotnet", "run", "-c", "Release", "--no-build"]